from typing import Annotated
from urllib.parse import urlencode

from fastapi import APIRouter, Depends, Response
from fastapi.responses import RedirectResponse

from app.api.dependencies import get_auth_service, get_current_user
from app.core.config import settings
from app.core.constants import UserRole
from app.core.cookies import clear_auth_cookie, set_auth_cookie
from app.core.exceptions import AppException
from app.core.security import CurrentUserClaims
from app.schemas.user import (
    GoogleExchangeRequest,
    PublicUserRegister,
    TokenResponse,
    UserCreate,
    UserLogin,
    UserResponse,
)
from app.services.auth_service import AuthService

router = APIRouter(prefix="/auth", tags=["auth"])


@router.post("/register", response_model=UserResponse)
async def register(
    payload: PublicUserRegister,
    auth_service: Annotated[AuthService, Depends(get_auth_service)],
) -> UserResponse:
    """Register a new patient via public self-registration.

    Only patients may self-register through this endpoint. Doctor and admin
    accounts are provisioned through privileged admin flows so this endpoint
    cannot be used to escalate privileges by passing ``role`` in the body.
    """
    user_data = UserCreate(
        email=payload.email,
        password=payload.password,
        full_name=payload.full_name,
        role=UserRole.PATIENT,
    )
    return await auth_service.register(user_data)


@router.post("/login", response_model=TokenResponse)
async def login(
    payload: UserLogin,
    response: Response,
    auth_service: Annotated[AuthService, Depends(get_auth_service)],
) -> TokenResponse:
    """Login a local user and return an app JWT."""
    token_response = await auth_service.login(payload)
    set_auth_cookie(response, token_response.access_token)
    return token_response


@router.get("/me")
async def me(
    current_user: Annotated[CurrentUserClaims, Depends(get_current_user)],
) -> CurrentUserClaims:
    """Return current authenticated user claims."""
    return current_user


@router.get("/google")
async def google_login_url(
    auth_service: Annotated[AuthService, Depends(get_auth_service)],
) -> dict[str, str]:
    """Return the Google OAuth URL the frontend should redirect the user to.

    The URL is generated by Supabase's OAuth proxy. The user signs in on
    Google, Supabase redirects to ``/auth/google/callback`` with a one
    time auth code, and the callback below trades that for an app JWT.
    """
    url = auth_service.get_google_oauth_url()
    return {"url": url}


@router.get("/google/callback")
async def google_callback(
    code: str,
    auth_service: Annotated[AuthService, Depends(get_auth_service)],
) -> RedirectResponse:
    """Receive the Supabase auth code and redirect back to the frontend.

    On success, redirects to ``{frontend_url}/?auth_code=...&user_name=...``;
    the frontend then POSTs the auth code to ``/auth/google/exchange`` to
    receive the actual JWT, so the JWT itself never appears in a URL or
    browser history.

    On any error the redirect goes to ``{frontend_url}/?google_error=...``
    so the frontend can show a user-facing message rather than a raw 4xx
    JSON in the middle of the OAuth flow.
    """
    try:
        auth_code, user_name = await auth_service.handle_google_callback(code)
    except AppException as exc:
        params = urlencode({"google_error": exc.message})
        return RedirectResponse(f"{settings.frontend_url}/?{params}", status_code=302)

    params = urlencode({"auth_code": auth_code, "user_name": user_name})
    return RedirectResponse(f"{settings.frontend_url}/?{params}", status_code=302)


@router.post("/google/exchange", response_model=TokenResponse)
async def google_exchange(
    payload: GoogleExchangeRequest,
    response: Response,
    auth_service: Annotated[AuthService, Depends(get_auth_service)],
) -> TokenResponse:
    """Exchange a one-time Google auth code for the application JWT."""
    token_response = auth_service.exchange_auth_code(payload.auth_code)
    set_auth_cookie(response, token_response.access_token)
    return token_response


@router.post("/logout")
async def logout(response: Response) -> dict[str, str]:
    """Clear the browser auth cookie.

    Bearer tokens are stateless and remain valid until expiry; the logout
    endpoint only controls the browser cookie session.
    """
    clear_auth_cookie(response)
    return {"status": "logged_out"}
